// The numbers a document claims, checked against the repository.
//
// `README.md` announced 562 unit tests and version 0.39.0 while the repository was at 0.61.0 with
// 699; the French one still said 284 tests and 0.11.1. Nobody lied — a number written in prose has
// no reason to follow the thing it describes, and a figure that has to be remembered will be wrong
// by the next release. So it is checked, and `--fix` rewrites it.
//
// What counts as truth is deliberately cheap to compute: a test is a top-level `test(` in a test
// file, which is what `node:test` reports, and a task is a directory under `eval/tasks`. Running the
// suite to count it would make this a slow gate that nobody puts in CI.

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { argv, exit } from "node:process";

const fix = argv.includes("--fix");

/** Top-level tests in a directory of test files. Nested ones are subtests and are not counted. */
function countTests(dir, prefix) {
  let total = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      total += countTests(join(dir, entry.name), prefix);
      continue;
    }
    if (!entry.name.endsWith(".ts")) continue;
    total += (readFileSync(join(dir, entry.name), "utf8").match(new RegExp(`^${prefix}test\\(`, "gm")) ?? []).length;
  }
  return total;
}

const truth = {
  version: JSON.parse(readFileSync("package.json", "utf8")).version,
  unit: countTests("tests", ""),
  // The integration suite nests its tests inside one `suite(...)`, so they are indented.
  integration: countTests("src/test/suite", "  "),
  tasks: readdirSync("eval/tasks", { withFileTypes: true }).filter((e) => e.isDirectory()).length,
  decisions: readdirSync("docs/adr").filter((f) => /^\d{4}-.+\.md$/.test(f)).length,
  // The IBM i skills, which the course counts. Four families — a skill's family IS what makes it an
  // IBM i skill, so this is read from the source rather than remembered: the course said "forty"
  // while there were 41, and nothing could have noticed.
  ibmiSkills: (readFileSync("src/core/session/skills.ts", "utf8").match(
    /group: "(?:rpg|cl|dds|db2i)"/g,
  ) ?? []).length,
};

/**
 * Where a number is claimed, and which one it is.
 *
 * Listed rather than guessed: a regular expression loose enough to find every phrasing is also
 * loose enough to rewrite a number that was never a claim about this. A new claim is added here,
 * which is the moment somebody decides it is a claim.
 */
const CLAIMS = [
  { file: "README.md", pattern: /(\d+) tests \(node:test\)/g, of: "unit" },
  { file: "README.md", pattern: /\((\d+) tests, headless\)/g, of: "integration" },
  { file: "README.md", pattern: /`(\d+\.\d+\.\d+)` — used every day/g, of: "version" },
  { file: "docs/ROADMAP.md", pattern: /état à la version \*\*(\d+\.\d+\.\d+)\*\*/g, of: "version" },
  { file: "docs/ROADMAP.md", pattern: /\*\*(\d+) tests unitaires\*\*/g, of: "unit" },
  { file: "docs/ROADMAP.md", pattern: /\*\*(\d+) tests d'intégration/g, of: "integration" },
  // The published comparison table says how many tasks it is about, and a table that says 51 after
  // five more were added is wrong in the quietest possible way: nothing fails, the number is simply
  // no longer true. The table itself is regenerated by the harness; this keeps the claim honest in
  // the meantime.
  { file: "eval/QUALITY.md", pattern: /\((\d+) tasks\)/g, of: "tasks" },
  // The course says how many tasks the bench holds. Its VERSION line is deliberately NOT here — see
  // `npm run check:course`, which refuses the build instead of rewriting it, because reading what
  // changed is the work and the number is only the receipt.
  { file: "docs/cours/12-la-qualite-mesuree.md", pattern: /\*\*(\d+) tâches\*\*/g, of: "tasks" },
  // ⚠️ Both course indexes count the decision records, and this claim is here because of how it was
  // found: the French one said "vingt-six" while there were 37 — the exact rot the course spends a
  // page warning about, inside the course. It was invisible to this script for a reason worth
  // keeping: A NUMBER WRITTEN IN WORDS CANNOT BE CHECKED. It was rewritten as a digit, which is the
  // only form a guard can read, and now neither edition can drift.
  { file: "docs/cours/README.md", pattern: /(\d+) décisions motivées/g, of: "decisions" },
  { file: "docs/course/README.md", pattern: /(\d+) reasoned decisions/g, of: "decisions" },
  { file: "docs/cours/11-ibm-i.md", pattern: /(\d+) compétences IBM i/g, of: "ibmiSkills" },
  { file: "docs/course/11-ibm-i.md", pattern: /(\d+) IBM i skills/g, of: "ibmiSkills" },
  // The release runbook prints the commands with the counts they should print. It said 193 and 27
  // while the suites were at 1067 and 43 — a figure in a code block is exactly as perishable as one
  // in prose, and this one is read by somebody about to publish.
  { file: "docs/PUBLISHING.md", pattern: /# (\d+) tests \(node:test\)/g, of: "unit" },
  { file: "docs/PUBLISHING.md", pattern: /# (\d+) tests, headless/g, of: "integration" },
];

const wrong = [];
const touched = new Map();

for (const claim of CLAIMS) {
  const current = touched.get(claim.file) ?? readFileSync(claim.file, "utf8");
  const expected = String(truth[claim.of]);
  let found = false;
  const next = current.replace(claim.pattern, (whole, said) => {
    found = true;
    if (said === expected) return whole;
    wrong.push(`${claim.file}: says ${said} ${claim.of}, repository has ${expected}`);
    return whole.replace(said, expected);
  });
  if (!found) wrong.push(`${claim.file}: the ${claim.of} claim this checks for is no longer there`);
  touched.set(claim.file, next);
}

if (fix) {
  for (const [file, text] of touched) writeFileSync(file, text, "utf8");
  console.log(`Updated: version ${truth.version}, ${truth.unit} unit, ${truth.integration} integration, ${truth.tasks} eval tasks.`);
  exit(0);
}

if (wrong.length) {
  console.error("Numbers in the documentation no longer match the repository:\n");
  for (const line of wrong) console.error(`  ✗ ${line}`);
  console.error("\nRun `npm run check:numbers -- --fix`.");
  exit(1);
}
console.log(`✓ version ${truth.version}, ${truth.unit} unit tests, ${truth.integration} integration tests, ${truth.tasks} eval tasks.`);
